arb-dir: lib/strings
template-arb-file: goals_module_pt.arb
output-dir: lib/strings/gen
output-localization-file: goals_module_localizations.dart
output-class: GoalsModuleLocalizations
nullable-getter: false
header: |
  // coverage:ignore-file
