enum RepositoryFailureReason {
  // =======================================================
  /// General repository failure reasons
  // =======================================================
  connectionError,
  permissionDenied,

  /// An entity with the same id already exists in the repository.
  /// NEW ID MUST be generated by the domain
  /// and the operation retried.
  sameIdAlreadyExists,

  // =======================================================
  /// createAnnualRevenueGoal specific failure reasons
  // =======================================================
  annualGoalForYearAlreadyExists,
}
