import 'package:bits_goals_module/src/core/domain/value_objects/app_version.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('AppVersion', () {
    test('should store the string value correctly', () {
      const versionString = '1.0.0';
      const appVersion = AppVersion(versionString);

      expect(appVersion.value, equals(versionString));
    });

    test('should consider two instances equal if they have the same value', () {
      const version1 = AppVersion('1.2.3');
      const version2 = AppVersion('1.2.3');

      // Tests the equality generated by Equatable
      expect(version1, equals(version2));
      // Ensures the hashCodes match as well
      expect(version1.hashCode, equals(version2.hashCode));
    });

    test(
        'should consider two instances different if they have different values',
        () {
      const version1 = AppVersion('1.0.0');
      const version2 = AppVersion('2.0.0');

      expect(version1, isNot(equals(version2)));
      expect(version1.hashCode, isNot(equals(version2.hashCode)));
    });

    test('the props list should contain the exact version value', () {
      const versionString = '3.1.4';
      const appVersion = AppVersion(versionString);

      expect(appVersion.props, equals([versionString]));
    });

    test(
        'stringify should be enabled and return the correct string representation',
        () {
      const appVersion = AppVersion('1.0.0-beta.1');

      expect(appVersion.stringify, isTrue);
      // Equatable uses the class name and props to build the toString() output
      expect(appVersion.toString(), equals('AppVersion(1.0.0-beta.1)'));
    });
  });
}
