import 'package:bits_goals_module/src/core/domain/entities/action_log/action_type.dart';
import 'package:bits_goals_module/src/core/domain/value_objects/app_version.dart';
import 'package:bits_goals_module/src/core/domain/value_objects/device_info.dart';
import 'package:bits_goals_module/src/core/domain/value_objects/id_uuid_v7.dart';
import 'package:bits_goals_module/src/core/domain/value_objects/ip_address.dart';
import 'package:bits_goals_module/src/core/domain/value_objects/logged_in_user.dart';
import 'package:bits_goals_module/src/infra/config/goals_module_permission.dart';
import 'package:equatable/equatable.dart';

/// Represents an audit log entry for operations performed within the module.
///
/// This Entity follows strict DDD patterns for immutability and validation.
class ActionLog extends Equatable {
  /// Unique identifier for this log entry (UUID v7).
  final IdUuidV7 _id;

  /// The exact moment the action was effected (backend).
  /// Nullable because it MUST be generated by the backend.
  final DateTime? _occurredAt;

  // ==========================
  // Context Info (Who & Where)
  // ==========================

  final LoggedInUser _user;
  final IpAddress _userIpAddress;
  final DeviceInfo _userDeviceInfo;
  final AppVersion _appVersion;

  // ==========================
  // Action Info (What & How)
  // ==========================

  final GoalsModulePermission _requiredPermission;
  final ActionType _actionType;
  final String _useCaseId;

  /// Snapshots of data states
  final Map<String, dynamic>? _oldDataMapped;
  final Map<String, dynamic> _newDataMapped;

  // ========================
  // Constructor
  // ========================

  const ActionLog._({
    required IdUuidV7 id,
    DateTime? occurredAt,
    required LoggedInUser user,
    required IpAddress userIpAddress,
    required DeviceInfo userDeviceInfo,
    required AppVersion appVersion,
    required GoalsModulePermission requiredPermission,
    required ActionType actionType,
    required String useCaseId,
    required Map<String, dynamic> newDataMapped,
    Map<String, dynamic>? oldDataMapped,
  })  : _id = id,
        _occurredAt = occurredAt,
        _user = user,
        _userIpAddress = userIpAddress,
        _userDeviceInfo = userDeviceInfo,
        _appVersion = appVersion,
        _requiredPermission = requiredPermission,
        _actionType = actionType,
        _useCaseId = useCaseId,
        _oldDataMapped = oldDataMapped,
        _newDataMapped = newDataMapped;

  factory ActionLog.create({
    required LoggedInUser user,
    required IpAddress userIpAddress,
    required DeviceInfo userDeviceInfo,
    required AppVersion appVersion,
    required GoalsModulePermission requiredPermission,
    required ActionType actionType,
    required String useCaseId,
    required Map<String, dynamic> newDataMapped,
    Map<String, dynamic>? oldDataMapped,
  }) {
    // Ensure maps are unmodifiable if provided
    final safeOldData = oldDataMapped != null
        ? Map<String, dynamic>.unmodifiable(oldDataMapped)
        : null;
    final safeNewData = Map<String, dynamic>.unmodifiable(newDataMapped);

    return ActionLog._(
      id: IdUuidV7.generate(),
      user: user,
      userIpAddress: userIpAddress,
      userDeviceInfo: userDeviceInfo,
      appVersion: appVersion,
      requiredPermission: requiredPermission,
      actionType: actionType,
      useCaseId: useCaseId,
      oldDataMapped: safeOldData,
      newDataMapped: safeNewData,
    );
  }

  factory ActionLog.reconstruct({
    required IdUuidV7 id,
    required DateTime occurredAt,
    required LoggedInUser user,
    required IpAddress userIpAddress,
    required DeviceInfo userDeviceInfo,
    required AppVersion appVersion,
    required GoalsModulePermission requiredPermission,
    required ActionType actionType,
    required String useCaseId,
    required Map<String, dynamic> newDataMapped,
    required Map<String, dynamic> oldDataMapped,
  }) {
    // Ensure maps are unmodifiable
    final safeOldData = Map<String, dynamic>.unmodifiable(oldDataMapped);
    final safeNewData = Map<String, dynamic>.unmodifiable(newDataMapped);

    return ActionLog._(
      id: id,
      occurredAt: occurredAt,
      user: user,
      userIpAddress: userIpAddress,
      userDeviceInfo: userDeviceInfo,
      appVersion: appVersion,
      requiredPermission: requiredPermission,
      actionType: actionType,
      useCaseId: useCaseId,
      oldDataMapped: safeOldData,
      newDataMapped: safeNewData,
    );
  }

  // =========================
  // Getters
  // =========================

  IdUuidV7 get id => IdUuidV7.fromString(_id.value);

  DateTime? get occurredAt => _occurredAt == null
      ? null
      : DateTime.fromMillisecondsSinceEpoch(_occurredAt.millisecondsSinceEpoch);

  LoggedInUser get user => LoggedInUser.create(
        uid: _user.uid,
        displayName: _user.displayName,
        email: _user.email.value,
        roleName: _user.roleName,
      );

  IpAddress get userIpAddress => IpAddress(_userIpAddress.value);

  DeviceInfo get userDeviceInfo => DeviceInfo(_userDeviceInfo.value);

  AppVersion get appVersion => AppVersion(_appVersion.value);

  GoalsModulePermission get requiredPermission => _requiredPermission;

  ActionType get actionType => _actionType;

  String get useCaseId => _useCaseId.toString();

  /// Returns a safe copy of the map to prevent external mutation
  Map<String, dynamic>? get oldDataMapped =>
      _oldDataMapped != null ? Map.unmodifiable(_oldDataMapped) : null;

  Map<String, dynamic> get newDataMapped => Map.unmodifiable(_newDataMapped);

  // =========================
  // Equatable Overrides
  // =========================

  @override
  List<Object?> get props => [
        _id,
        _occurredAt,
        _user,
        _userIpAddress,
        _userDeviceInfo,
        _appVersion,
        _requiredPermission,
        _actionType,
        _useCaseId,
        _oldDataMapped,
        _newDataMapped,
      ];

  @override
  bool get stringify => true;
}
